# Generated by Django 3.0.3 on 2020-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingmodel',
            name='subincidenttypes',
            field=models.ManyToManyField(blank=True, to='testapp.Subincidenttype', verbose_name='subincident types'),
        ),
    ]
